version: '3.9'
services:
  app:
    image: node:19-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - postgres_db
    environment:
      # # # Development database
      DEV_DB_USERNAME: postgres
      DEV_DB_HOSTNAME: postgres_db
      DEV_DB_NAME: sw_dev_db
      DEV_DB_PASSWORD: password
      DEV_DB_PORT: 5432
      # # # Test database
      CI_DB_USERNAME: postgres
      CI_DB_HOSTNAME: postgres_db
      CI_DB_NAME: sw_test_db
      CI_DB_PASSWORD: password
      CI_DB_PORT: 5432
      # # # Production database
      PROD_DB_USERNAME: postgres
      PROD_DB_HOSTNAME: postgres_db
      PROD_DB_NAME: sw_prod_db
      PROD_DB_PASSWORD: password
      PROD_DB_PORT: 5432
  postgres_db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: sw_dev_db
volumes:
  pgdata: